board/urls.py
from django.urls import path, include
from board import views

urlpatterns = [
    path('create/', views.create_board, name='board-create'),
    path('<int:board_id>/', views.board_view, name='board-view'),
    path('<int:board_id>/view/<str:view>/', views.board_change_view, name='board-change-view'),
    path('invite/<uuid:board_uuid>/', views.board_invite_view, name='board-invite'),
    path('search/', views.search_boards, name='board-search'),
    path('<int:board_id>/reports/', views.board_reports, name='board-reports'),
    path('<int:board_id>/create_column/', views.create_column, name='column-create'),
    path('<int:board_id>/columns/', views.load_columns, name='board-columns'),
    path('<int:board_id>/columns/<int:column_id>/', views.get_task_lists, name='get_task_lists'),
    path('<int:board_id>/columns/<int:column_id>/update_name/', views.update_column_name, name='update_column_name'),
    path('<int:board_id>/columns/<int:column_id>/delete/', views.delete_column, name='column-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/detail/', views.detail_task, name='task-detail'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/move/', views.task_move, name='task-move'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/history/', views.history_task, name='task-history'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/edit/', views.edit_task, name='task-edit'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/delete/', views.delete_task, name='task-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/toggle/', views.task_status_toggle, name='task-status-toggle'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/', views.get_sub_task_lists, name='get_sub_task_list'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/create/', views.create_sub_task, name='sub-task-create'),
    
    path('<int:board_id>/tasks/create/', views.create_task, name='task-create'),
    path('tasks/<int:task_id>/add_comment/', views.add_comment, name='add_comment'),
    path('tasks/<int:task_id>/move/', views.move_task, name='task-move'),

    # path('api/', include(router.urls)),
    path('api/boards/', views.BoardViewSet.as_view({'get': 'list', 'post':'create'}), name='board_list'),
    path('api/boards/<int:pk>/', views.BoardViewSet.as_view({'get': 'retrieve', 'delete':'destroy', 'put':'update', 'patch':'partial_update'}), name='board_detail'),

    path('api/boards/<int:board_id>/columns/', views.ColumnViewSet.as_view({'post': 'create', 'get':'list'}), name='create_column'),
    path('api/boards/<int:board_id>/columns/<int:pk>/', views.ColumnViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='column_detail'),
    
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/', views.TaskViewSet.as_view({'post':'create'}), name='create_task'),
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/<int:pk>/', views.TaskViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='task_detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from board import urls as board_urls
from accounts import urls as accounts_urls
from notifications import urls as notification_urls
from task_manager import settings
from workspace import urls as workspace_urls
from django.conf.urls.static import static


@login_required
def index(request):
    return redirect('workspace:index')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hijack/', include('hijack.urls')),
    path('',index, name='index'),
    path('auth/', include((accounts_urls, 'accounts'), namespace='accounts')),
    path('board/', include((board_urls, 'board'), namespace='board')),
    path('notification/', include((notification_urls, 'notifications'), namespace='notifications')),
    path('workspace/', include((workspace_urls, 'workspace'), namespace='workspace')),
]



if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workspace/urls.py
from django.urls import path, include
from workspace import views


urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.workspace_create, name='workspace_create'),
    path('<int:workspace_id>/', views.get_workspace_boards, name='get_workspace_boards'),
    path('<int:workspace_id>/actions', views.workspace_actions, name='workspace_actions'),
    path('<int:workspace_id>/board/<int:board_id>/board_actions/', views.board_actions, name='board-actions'),
    path('invite/<uuid:workspace_uuid>/', views.workspace_invite_view, name='workspace-invite'),
]

board/views.py
from collections import defaultdict
from datetime import date, datetime, timedelta
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import QueryDict
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Page
from django.db.models import QuerySet, Count, Sum, Avg, Q
from rest_framework import viewsets, filters
from rest_framework.decorators import action
from rest_framework.response import Response
from django_htmx.http import HttpResponseClientRedirect
from accounts.models import Users
from board.forms import BoardCreateForm, BoardForm, CommentForm, TaskCreateForm, TaskFilterForm, TaskForm
from board.models import Attachment, Board, BoardFilter, Column, Comments, Task
from board.permissions import IsBoardMemberOrReadOnly
from board.serializers import BoardSerializer, ColumnSerializer, TaskSerializer, BoardListSerializer
from board.filters import TaskFilter
from notifications.views import get_notifications
from task_manager.logger import logger


from django_filters.rest_framework import DjangoFilterBackend

from workspace.models import Workspace

import plotly.graph_objects as go
import json
import re



def task_lists(board_id:int, user:Users):
    board_filter = BoardFilter.objects.filter(board_id=board_id, user=user).only('filter').first()
    filters = Q(column__board_id=board_id, parent_task__isnull=True)
    if board_filter.filter:
        cd = board_filter.filter
        user_filter = Q()
        if cd.get('search'):
            filters &= Q(title__icontains=cd['search']) | Q(description__icontains=cd['search'])
        if cd.get('priority'):
            filters &= Q(priority=cd['priority'])
        if cd.get('is_complete') in ['true', 'false']:
            filters &= Q(is_complete=(cd['is_complete'] == 'true'))
        elif cd.get('is_complete')!='all':
            filters &= Q(is_complete=False)
        if cd.get('due_after'):
            filters &= Q(due_date__gte=cd['due_after'])
        if cd.get('due_before'):
            filters &= Q(due_date__lte=cd['due_before'])
        if cd.get('assigned_to'):
            user_filter &= Q(assigned_to__in=cd['assigned_to'])
        if cd.get('tags'):
            filters &= Q(tags__in=cd['tags'])
        logger.debug(f'{filters=}')
        if user_filter:
            logger.debug(f'{user_filter=}')
            tasks = Task.objects.prefetch_related('tags','assigned_to').filter(filters, user_filter).distinct()
        elif user.is_staff:
            tasks = Task.objects.prefetch_related('tags','assigned_to').filter(filters).distinct()
        else:
            tasks = user.assigned_tasks.prefetch_related('tags','assigned_to').filter(filters)
    elif user.is_staff:
        tasks = Task.objects.prefetch_related('tags','assigned_to').filter(filters).exclude(is_complete=True)
    else:
        logger.debug(f'{filters=}')
        tasks = user.assigned_tasks.prefetch_related('tags','assigned_to').filter(filters).exclude(is_complete=True)
    return tasks

def normalize_querydict(querydict: QueryDict) -> dict:
    """
    Converts a QueryDict to a standard dict:
    - Flattens single-item lists
    - Preserves multi-item lists
    """
    return {
        key: values if len(values) > 1 else values[0]
        for key, values in querydict.lists()
    }


@login_required
def search_boards(request):
    q = request.GET.get("board_search", "")
    boards:list[Board] = []
    if q:
        ids= Column.objects.select_related('board').filter(board__name__icontains=q, board__members=request.user).exclude(draft_column=True).values_list('board_id',flat=True)
        logger.debug(f'{ids=}')
        boards = request.user.board_memberships.select_related("workspace").filter(id__in=set(ids))
    return render(request, "boards/components/board_card_list.html", {"boards": boards})

@login_required
def load_columns(request, board_id):
    columns = Column.objects.filter(board_id=board_id).exclude(draft_column=True)
    return render(request, "boards/components/column_dropdown.html", {"columns": columns})


@login_required
def board_view(request, board_id):
    context:dict = {}
    board:Board = get_object_or_404(Board, pk=board_id, members=request.user)
    board_filter, _ = BoardFilter.objects.get_or_create(board=board, user=request.user)
    context['active_board'] = board
    context['board_filter'] = board_filter
    context['columns'] = board.columns.all()
    if request.htmx:
        context['board'] = board
        context['task_form'] = TaskForm(workspace=board.workspace, user=request.user,)
        triggers = {}
        triggers["boardLoaded"] = {"board_id":  board_id, "level": "info"}
        if request.method=='POST':
            logger.debug(f'{request.POST=}')
            if not request.POST.get('clear'):
                filter_form = TaskFilterForm(board=board, data=request.POST)
                q = QueryDict('', mutable=True)
                q.update(filter_form.data)
                logger.debug(f'{q=}')
                data = normalize_querydict(q)

                logger.debug(f'{data=}')
                board_filter.filter = data
                triggers["showToast"] = {"message":"Task Filtered", "level":"success"}
            else:
                board_filter.filter = {}
                board_filter.filter.pop('csrfmiddlewaretoken',None)
                triggers["showToast"] = {"message":"Task Filter Cleared", "level":"danger"}
            
            board_filter.save()
            triggers["filterSubmitted"] = {"board_id":  board_id, "level": "info"}
            triggers["closeModal"] = {"modal_id": "close_filterBoard", "level": "info"}
        context['filter_form'] = TaskFilterForm(board=board, initial=board_filter.filter)
        tasks = task_lists(board_id=board_id, user=request.user)
        column_map:dict[Column,list[Task]] = {column:[] for column in board.columns.all()}
        for task in tasks:
            if task.column not in column_map:
                column_map[task.column]=[]
            column_map[task.column].append(task)
        logger.debug(f'{column_map=}')
        context['column_map'] = column_map
        context['tasks'] = tasks
        response = render(request, 'boards/components/board.html', context)
        response['HX-Trigger'] = json.dumps(triggers)
    else:
        context['active_board'] = board
        context['boards'] = [board]
        context['workspace_id'] = board.workspace_id
        context['users'] = board.members.all()
        context['unread_notification_count'] = request.user.notifications.filter(read=False).count()
        context:dict = get_notifications(user=request.user, page_number=1, context=context)
        context['view_name'] = 'Board'
        context['board_create_form'] = BoardCreateForm(user=request.user)
        logger.debug(context)
        response = render(request, 'boards/index.html', context)
    return response

@login_required
def board_change_view(request, board_id, view):
    board:Board = get_object_or_404(Board, pk=board_id, members=request.user)
    board_filter = BoardFilter.objects.filter(user=request.user, board=board).first()
    board_filter.board_view = view
    board_filter.save(update_fields=['board_view'])
    return redirect('board:board-view',board_id=board_id)


@login_required
def board_reports(request, board_id):
    context:dict = {}
    board:Board = get_object_or_404(Board, pk=board_id, members=request.user)
    context['active_board'] = board
    logger.debug(board.created_at)
    context['boards'] = Board.objects.filter(workspace=board.workspace).only('id','name')
    
    board_tasks = Task.objects.filter(column__board=board, parent_task__isnull=True)
    # board_tasks = Task.objects.filter(column__board=board)
    tasks_by_priority = list(board_tasks.values('priority').annotate(count=Count('id')))
    tasks_by_column = list(board_tasks.values('column__name').annotate(count=Count('id')))
    
    aggregates = board_tasks.aggregate(
        total_tasks=Count('id'),
        completed_tasks=Count('id', filter=Q(is_complete=True)),
        incomplete_tasks=Count('id', filter=Q(is_complete=False)),
        overdue_tasks=Count('id', filter=Q(is_complete=False, due_date__lt=date.today())),
        high_priority_tasks=Count('id', filter=Q(priority='High')),
    )
    assigned_tasks = board_tasks.filter(assigned_to__isnull=False).distinct().count()
    task_summary = { **aggregates, 'assigned_tasks': assigned_tasks}
    logger.debug(f'{task_summary=}')
    context['task_summary'] = task_summary
    # Process data for Plotly
    priority_labels = [item["priority"] for item in tasks_by_priority]
    priority_values = [item["count"] for item in tasks_by_priority]

    column_labels = [item["column__name"] for item in tasks_by_column]
    column_values = [item["count"] for item in tasks_by_column]
    tasks = board_tasks.values(
        "title", "created_at", "updated_at", "priority", "column__name", "is_complete","due_date"
    )

    logger.debug(tasks)
    task_list:list[dict] = []
    today_date = date.today()

    for task in tasks:
        created: datetime = task["created_at"]
        updated: datetime = task["updated_at"]
        due_date: date = task.get("due_date")

        created_str = created.strftime("%Y-%m-%d")
        updated_str = updated.strftime("%Y-%m-%d")
        
        task_title = task["title"]
        column = task["column__name"]
        priority = task["priority"]

        if task["is_complete"]:
            # Segment 1: Active work time
            days = (updated.date() - created.date()).days
            task_list.append({
                "Task": task_title,
                "Start": created_str,
                "Finish": updated_str,
                "Resource": priority,

templates/boards/components/board.html
{% load static board_tags %}
{% if board_filter.board_view == 'table' %}
{% include "boards/components/table_view.html" with board=board tasks=tasks columns=columns %}
{% else %}
{% include "boards/components/card_view.html" with board=board column_map=column_map %}
{% endif %}

<button class="btn btn-sm btn-outline-primary {% if filter_form.initial %}active{% endif %}" id="filter_board_{{board.id}}_btn"
        title="Filters"
        data-bs-toggle="modal"
        data-bs-target="#filterBoard"
        hx-swap-oob="true">
    <i class="fa-solid fa-filter"></i>
</button>


<div class="modal-body" id="filter_board_modal" hx-swap-oob="true">
    <form hx-post="{% url 'board:board-view' board.id %}" hx-target="#main-content" hx-swap="innerHTML" hx-indicator="#loader">
        {% csrf_token %}
        {% include 'form.html' with form=filter_form %}
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Filter</button>
            {% if filter_form.initial %}
            <button type="submit" hx-params='{"clear":"true"}' name="clear" value="true" class="btn btn-danger">Clear</button>
            {% endif %}
        </div>
    </form>
</div>

templates/boards/components/board_edit.html
            <form id="edit_board_form" name="edit_board_form" hx-post="{% url "workspace:board-actions" form.instance.workspace_id form.instance.id %}" hx-target="#board-{{ form.instance.id }}" hx-swap="outerHTML">
                {% include 'form.html' with form=form %}
            </form>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="edit_board_form">Save Changes</button>
            </div>

templates/boards/components/column_create.html
    <form id="create_column_form" 
            method="POST"
            action="{% url 'board:column-create' board.id %}" 
            hx-post="{% url 'board:column-create' board.id %}" 
            hx-swap="none"
            >
        {% csrf_token %}
        <div class="mb-3">
            <label for="column_name" class="form-label">Column Name</label>
            <input type="text" class="form-control" id="column_name" name="name" required>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Create Column</button>
        </div>
    </form>

templates/boards/components/create.html
<form hx-post="{% url 'board:task-create' board_id=board_id column_id=column_id %}" >
    {% csrf_token %}
    {% include 'form.html' with form=form %}

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Cancel</button>
    </div>
</form>

templates/boards/components/sub_task_list.html
<div id="sub_task_list">
  {% for task in sub_tasks %}
    <div class="task-card" id="sub_task_{{ task.id }}">
      <input type="checkbox"
              {% if task.is_complete %}checked{% endif %}
              hx-post="{% url 'board:task-status-toggle' board_id=board_id column_id=task.column_id task_id=task.id %}" 
              hx-target="#sub_task_{{ task.id }}" 
              hx-swap="outerHTML"
              title="Mark as complete">

      <!-- Sub-task title with strike-through if completed -->
      <p class="subtask-title {% if task.is_complete %}completed-text{% endif %}"
          hx-get="{% url 'board:task-edit' board_id=board_id column_id=column_id task_id=task.id %}" 
          hx-target="#edit_task_modal" 
          hx-swap="innerHTML">
        {{ task.title }}
      </p>
    </div>
  {% endfor %}
</div>


<button class="btn btn-primary"
    hx-get="{% url 'board:sub-task-create' board_id=board_id column_id=column_id task_id=task_id %}" 
    hx-target="#edit_task_modal" 
    hx-swap="innerHTML">Create Sub Task
</button>
<button class="btn btn-warning"
    hx-get="{% url 'board:task-edit' board_id=board_id column_id=column_id task_id=task_id %}" 
    hx-target="#edit_task_modal" 
    hx-swap="innerHTML">View Parent Task
</button>

templates/boards/components/task_card_new.html
{% load board_tags %}
<div class="task-card p-2 mb-2 bg-white border transition-shadow rounded shadow-sm border-start priority-{{ task.priority|lower }}"
     id="task_{{ task.id }}"
     draggable="true"
     data-task-id="{{ task.id }}"
     onmouseover="showCompleteTaskCheckBox(this)"
     onmouseout="hideCompleteTaskCheckBox(this)">

  <!-- Main Content -->
  <div class="d-flex flex-column flex-grow-1">
    
    <!-- Title Row -->
    <div class="d-flex justify-content-between align-items-center mb-2">
      <div class="d-flex cursor pointer flex-grow-1">
        <input type="checkbox"
              class="form-check-input me-2 complete_task d-none"
              id="task_toggle_{{task.id}}"
              {% if task.is_complete %}checked{% endif %}
              hx-post="{% url 'board:task-status-toggle' board_id=board_id column_id=task.column_id task_id=task.id %}"
              hx-target="#task_{{ task.id }}"
              hx-swap="delete"
              title="Mark as complete" />
        {% if task.priority == 'High' %}
          <span class="me-1" title="Priority: {{task.priority}}">
            <i class="fa-regular fa-flag text-danger"></i>
          </span>
        {% elif task.priority == 'Medium' %}
          <span class="me-1" title="Priority: {{task.priority}}">
            <i class="fa-regular fa-flag text-warning"></i>
          </span>
        {% elif task.priority == 'Low' %}
          <span class="me-1" title="Priority: {{task.priority}}">
            <i class="fa-regular fa-flag text-secondary"></i>
          </span>
        {% else %}
          <span class="me-1">
            <i class="fa-regular fa-flag text-secondary"></i>
          </span>
        {% endif %}
        <p id="task_title_{{task.id}}"
            class="flex-grow-1 mb-0 fw-semibold task-title text-wrap task-title-truncated {% if task.is_complete %}text-decoration-line-through text-muted{% endif %}"
            hx-get="{% url 'board:task-detail' board_id=board_id column_id=task.column_id task_id=task.id %}"
            hx-target="#edit_task_modal"
            hx-swap="innerHTML"
            data-bs-toggle="modal"
            data-bs-target="#editTaskModal"
            title="{{ task.title }}">
            {{ task.title }}
        </p>
        
      </div>
      <!-- Delete Button (no changes needed here) -->
      {% if task.created_by == request.user %}
      <button class="btn p-0 border-0 ms-2 delete_task d-none"
              id="task_delete_{{task.id}}"
              hx-delete="{% url 'board:task-delete' board_id=board_id column_id=task.column_id task_id=task.id %}"
              hx-target="#task_{{ task.id }}"
              hx-swap="delete"
              hx-confirm="Are you sure?"
              title="Delete Task">
        <i class="fas fa-trash-alt text-danger"></i>
      </button>
      {% endif %}
    </div>

    <!-- Consolidated Footer -->
    <div class="footer d-flex justify-content-between align-items-center">

      <!-- Left: Tags -->
      <div class="tags-container d-flex flex-wrap gap-1">
        {% for tag in task.tags.all %}
          <span class="badge small" title="Tag: {{tag}}" style="background-color:{{tag.color}}">{{ tag }}</span>
        {% endfor %}
      </div>

      <!-- Right: Meta Icons & Users -->
      <div class="meta-container d-flex align-items-center gap-2 text-muted small">
        
        
        <div class="d-flex flex-column">
          {% if task.assigned_to.exists %}
          <div class="assigned_users d-flex">
            {% comment %} {% with task|assigned_users as users %}
            {% for user in users %}
            <div class="assigned_user" title="{{user.name|default:user.username}} ({{user.email}})">{{user|initials}}</div>
            {% endfor %}
            {% endwith %} {% endcomment %}

            {% with task|assigned_users as users %}
              {% for user in users|slice:":2" %}
                <div class="p-1 assigned_user {% if not forloop.first %}second{% endif %}" title="{{user.name|default:user.username}} ({{user.email}})">{{user|initials}}</div>
              {% endfor %}
              {% if users|length > 2 %}
                <div class="p-1 assigned_user second" title="{{ users|length|add:"-2" }} more users assigned">+{{ users|length|add:"-2" }}</div>
              {% endif %}
            {% endwith %}
          </div>
          {% endif %}
          <div class="d-flex gap-3">
            {% if task.total_sub_tasks > 0 %}
            <div class="check-counter" title="Sub Tasks: {{task.completed_sub_tasks}} of {{task.total_sub_tasks}} complete">
              <i class="far fa-square-check"></i> {{task.completed_sub_tasks}}/{{task.total_sub_tasks}}
            </div>
            {% endif %}

            <div class="datetime mt-1 text-small text-muted" title="Last Updated: {{ task.updated_at|date:'M d, Y h:i A' }}">
              <span><i class="fa-regular fa-clock"></i></span> {{ task.updated_at|date:"M d, H:i" }}
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>

templates/boards/components/task_edit.html
<div class="d-flex gap-1">
    <div class="container py-3" id="form_div" style="width:50%;">
        <div class="task-container">
            {% include 'boards/components/edit_form.html' with task=task form=form sub_tasks=sub_tasks board_id=board_id column_id=task.column_id %}
            {% if not task.parent_task %}
            <div class="mb-3" id="sub_task_list">
                <label class="form-label">Sub Tasks:</label>
                <form id="create_sub_task_form"
                    name="create_sub_task_form"
                    class="d-flex mt-2"
                    hx-post="{% url 'board:sub-task-create' board_id=board_id column_id=task.column_id task_id=task.id %}" 
                    hx-target="#sub_task_container" 
                    hx-swap="beforeend"
                    >
                    {% csrf_token %}
                    <input type="text" name="title" placeholder="New Sub task" class="form-control me-2" required>
                    <button type="submit" class="btn btn-light fw-bold add-sub-task">Add</button>
                </form>
                <div id="sub_task_container" class="p-3">
                    {% for sub_task in sub_tasks %}
                    {% include 'boards/components/sub_task_card.html' with sub_task=sub_task %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
                
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" form="edit_task_form">Save Changes</button>
            {% if task.parent_task %}
            <button type="button" class="btn btn-warning"
            hx-get={% url 'board:task-edit' board_id=board_id column_id=column_id task_id=task.parent_task_id %}
            hx-target="#edit_task_modal"
            hx-swap="innerHTML"
            >Back</button>                
            {% endif %}
        </div>
    </div>
    <div class="container py-3" id="comment_div" style="width:50%">
        <div class="chat-container">
            <!-- Scrollable Messages Section -->
            <div id="chatMessages" class="auto-hide-scrollbar chat-messages mb-3 overflow-scroll d-flex flex-column">
                {% for comment in comments %}
                {% include 'boards/components/comment.html' with comment=comment %}
                {% endfor %}
            </div>
            <!-- Input Form -->
            <form id="comment_form" class="d-flex gap-1 chat-input" hx-post="{% url 'board:add_comment' task.id %}" hx-target="#chatMessages" hx-swap="beforeend">
                <div class="input-group">
                    <!-- Separate wrapper to position mention box correctly -->
                    <div class="position-relative w-100">
                        <input name="comment" type="text" id="chatInput" class="form-control" placeholder="Type a message..." required>
                        <ul id="mentionSuggestions" class="list-group position-absolute d-none w-100" style="top: 100%; left: 0; z-index: 1000;"></ul>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Send</button>
            </form>
        </div>
    </div>
</div>

templates/boards/components/task_move.html
    <div id="task_move">
      <form id="task_move_form" name="task_move_form" hx-post="{% url 'board:task-move' board_id=board_id column_id=task.column_id task_id=task.id %}" hx-swap="none" hx-indicator="#loader">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title">Move Task: {{ task.title }}</h5>
        </div>
        <div class="modal-body">
          <input type="hidden" name="board" value="{{task.column.board_id}}">

          <!-- Searchable Board -->
          <div class="m-3">
            <label for="board_search">Board</label>

            <!-- Search input -->
            <input 
              type="text" 
              class="form-control mb-2"
              placeholder="Search boards..." 
              hx-get="{% url 'board:board-search' %}" 
              hx-target="#board-search-list"
              hx-trigger="keyup changed delay:500ms"
              hx-swap="innerHTML"
              id="board_search"
              name="board_search"
              onfocus="document.getElementById('board-search-list').classList.remove('d-none')"
            >
          </div>

          <!-- Selected board preview -->
          <div id="selected-board-wrapper" class="m-3">
            <div class="card p-2 mb-2" style="border: 1px solid #ccc;">
              <strong>{{ task.column.board.name }}</strong><br>
              <small class="text-muted">{{ task.column.board.workspace.name }}</small>
            </div>
          </div>

          <!-- Board search result list -->
          <div id="board-search-list" class="m-3 d-none">
            {% include "boards/components/board_card_list.html" with boards=boards current_board=task.column.board %}
          </div>


          <!-- Selected Column -->
          <div id="column-select" class="m-3">
            {% include "boards/components/column_dropdown.html" with columns=columns current_column=task.column %}
          </div>
          
          <!-- Move to Column -->
          {% if task.parent_task %}
          <div id="move-to-column" class="m-3" style="height:15px;">
            <input type="checkbox" class="form-check-input" id="convertCheckbox" name="convert_to_main_task">
            <label class="form-check-label" for="convertCheckbox">Convert to Task Card</label>
          </div>
          {% endif %}

        </div>

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Move</button>
        </div>
      </form>
    </div>


<button class="btn btn-outline-danger btn-sm" id="task_move"
  hx-get="{% url 'board:task-detail' board_id=board_id column_id=task.column_id task_id=task.id %}?from=task_detail"
  hx-target="#edit_task_modal"
  hx-swap="innerHTML"
  title="Task Detail"
  hx-swap-oob="true">
  <i class="fa-solid fa-xmark"></i>
</button>