accounts/urls.py
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('register/', views.register_user, name='register-user'),
    path('register/success/', views.account_created_msg, name='account_created_msg'),
    path('login/', views.email_login, name='login-user'),
    path('logout/', views.logout_user, name='logout-user'),
    path('api-auth/', include('rest_framework.urls')),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'), 
]

board/urls.py
from django.urls import path, include
from board import views

urlpatterns = [
    path('create/', views.create_board, name='board-create'),
    path('<int:board_id>/', views.board_view, name='board-view'),
    path('<int:board_id>/view/<str:view>/', views.board_change_view, name='board-change-view'),
    path('invite/<uuid:board_uuid>/', views.board_invite_view, name='board-invite'),
    path('search/', views.search_boards, name='board-search'),
    path('<int:board_id>/reports/', views.board_reports, name='board-reports'),
    path('<int:board_id>/create_column/', views.create_column, name='column-create'),
    path('<int:board_id>/columns/', views.load_columns, name='board-columns'),
    path('<int:board_id>/columns/<int:column_id>/', views.get_task_lists, name='get_task_lists'),
    path('<int:board_id>/columns/<int:column_id>/update_name/', views.update_column_name, name='update_column_name'),
    path('<int:board_id>/columns/<int:column_id>/delete/', views.delete_column, name='column-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/detail/', views.detail_task, name='task-detail'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/move/', views.task_move, name='task-move'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/history/', views.history_task, name='task-history'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/edit/', views.edit_task, name='task-edit'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/delete/', views.delete_task, name='task-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/toggle/', views.task_status_toggle, name='task-status-toggle'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/', views.get_sub_task_lists, name='get_sub_task_list'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/create/', views.create_sub_task, name='sub-task-create'),
    
    path('<int:board_id>/tasks/create/', views.create_task, name='task-create'),
    path('tasks/<int:task_id>/add_comment/', views.add_comment, name='add_comment'),
    path('tasks/<int:task_id>/move/', views.move_task, name='task-move'),

    # path('api/', include(router.urls)),
    path('api/boards/', views.BoardViewSet.as_view({'get': 'list', 'post':'create'}), name='board_list'),
    path('api/boards/<int:pk>/', views.BoardViewSet.as_view({'get': 'retrieve', 'delete':'destroy', 'put':'update', 'patch':'partial_update'}), name='board_detail'),

    path('api/boards/<int:board_id>/columns/', views.ColumnViewSet.as_view({'post': 'create', 'get':'list'}), name='create_column'),
    path('api/boards/<int:board_id>/columns/<int:pk>/', views.ColumnViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='column_detail'),
    
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/', views.TaskViewSet.as_view({'post':'create'}), name='create_task'),
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/<int:pk>/', views.TaskViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='task_detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from board import urls as board_urls
from accounts import urls as accounts_urls
from notifications import urls as notification_urls
from task_manager import settings
from workspace import urls as workspace_urls
from django.conf.urls.static import static


@login_required
def index(request):
    return redirect('workspace:index')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hijack/', include('hijack.urls')),
    path('',index, name='index'),
    path('auth/', include((accounts_urls, 'accounts'), namespace='accounts')),
    path('board/', include((board_urls, 'board'), namespace='board')),
    path('notification/', include((notification_urls, 'notifications'), namespace='notifications')),
    path('workspace/', include((workspace_urls, 'workspace'), namespace='workspace')),
]



if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/navbar.html
    {% load static %}
    <div id="loader">
        <div id="loader_div">
            <span class="loader"></span>
        </div>
    </div>
    <!-- Navbar -->
    <nav class="navbar navbar-light shadow-sm px-4 py-2 bg-white sticky-top">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            
              <!-- Logo & Title -->
            <div class="navbar-brand d-flex align-items-center gap-2">
                <a href="{% url 'workspace:index' %}">
                <img src="{% static 'images/task_master.png' %}" alt="TaskMaster Logo" class="navbar-logo" height="40">
                </a>
                <h3 class="fw-bold mb-0 text-primary">{{view_name}}</h3>
            </div>
        
            <!-- User Info, Notifications & Logout -->
            <div class="user-info d-flex align-items-center gap-3">
                <span class="text-muted">Welcome, {{ user.username }}</span>
                <button id="darkModeToggle" onclick="toggleDarkmode()">🌙</button>
                  <!-- Notifications -->
                <div class="position-relative">
                    <span class="btn btn-light rounded-circle shadow-sm notifications-btn" title="Notifications">
                        <i class="fa-solid fa-bell text-primary"></i>
                        {% if unread_notification_count > 0 %}
                        <span id="unread_notification_count" class="position-absolute top-0 start-100 translate-middle notification-badge rounded-pill bg-danger">
                        {{ unread_notification_count }}
                        </span>
                        {% endif %}
                    </span>
                </div>
                
                <div class="position-relative">
                    <span class="btn btn-light rounded-circle shadow-sm work-logout-btn" title="Logout" hx-delete="{% url 'accounts:logout-user' %}" hx-swap="none">
                        <i class="fa-solid fa-right-from-bracket"></i>
                    </span>
                </div>
            </div>
        </div>
    </nav>
    <!-- Notifications Dropdown (Initially Hidden) -->
    <div id="notification-div" class="notification-dropdown fade">
        <div id="notification-list">
            {% include 'notifications/notification_list.html' with notifications=notifications %}
        </div>
        <div class="notification-loader"><div></div><div></div><div></div></div>
    </div>