board/urls.py
from django.urls import path, include
from board import views

urlpatterns = [
    path('create/', views.create_board, name='board-create'),
    path('<int:board_id>/', views.board_view, name='board-view'),
    path('<int:board_id>/view/<str:view>/', views.board_change_view, name='board-change-view'),
    path('invite/<uuid:board_uuid>/', views.board_invite_view, name='board-invite'),
    path('search/', views.search_boards, name='board-search'),
    path('<int:board_id>/reports/', views.board_reports, name='board-reports'),
    path('<int:board_id>/create_column/', views.create_column, name='column-create'),
    path('<int:board_id>/columns/', views.load_columns, name='board-columns'),
    path('<int:board_id>/columns/<int:column_id>/', views.get_task_lists, name='get_task_lists'),
    path('<int:board_id>/columns/<int:column_id>/update_name/', views.update_column_name, name='update_column_name'),
    path('<int:board_id>/columns/<int:column_id>/delete/', views.delete_column, name='column-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/detail/', views.detail_task, name='task-detail'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/move/', views.task_move, name='task-move'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/history/', views.history_task, name='task-history'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/edit/', views.edit_task, name='task-edit'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/delete/', views.delete_task, name='task-delete'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/toggle/', views.task_status_toggle, name='task-status-toggle'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/', views.get_sub_task_lists, name='get_sub_task_list'),
    path('<int:board_id>/columns/<int:column_id>/tasks/<int:task_id>/sub_tasks/create/', views.create_sub_task, name='sub-task-create'),
    
    path('<int:board_id>/tasks/create/', views.create_task, name='task-create'),
    path('tasks/<int:task_id>/add_comment/', views.add_comment, name='add_comment'),
    path('tasks/<int:task_id>/move/', views.move_task, name='task-move'),

    # path('api/', include(router.urls)),
    path('api/boards/', views.BoardViewSet.as_view({'get': 'list', 'post':'create'}), name='board_list'),
    path('api/boards/<int:pk>/', views.BoardViewSet.as_view({'get': 'retrieve', 'delete':'destroy', 'put':'update', 'patch':'partial_update'}), name='board_detail'),

    path('api/boards/<int:board_id>/columns/', views.ColumnViewSet.as_view({'post': 'create', 'get':'list'}), name='create_column'),
    path('api/boards/<int:board_id>/columns/<int:pk>/', views.ColumnViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='column_detail'),
    
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/', views.TaskViewSet.as_view({'post':'create'}), name='create_task'),
    path('api/boards/<int:board_id>/columns/<int:column_id>/tasks/<int:pk>/', views.TaskViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put':'update', 'patch':'partial_update', }), name='task_detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from board import urls as board_urls
from accounts import urls as accounts_urls
from notifications import urls as notification_urls
from task_manager import settings
from workspace import urls as workspace_urls
from django.conf.urls.static import static


@login_required
def index(request):
    return redirect('workspace:index')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hijack/', include('hijack.urls')),
    path('',index, name='index'),
    path('auth/', include((accounts_urls, 'accounts'), namespace='accounts')),
    path('board/', include((board_urls, 'board'), namespace='board')),
    path('notification/', include((notification_urls, 'notifications'), namespace='notifications')),
    path('workspace/', include((workspace_urls, 'workspace'), namespace='workspace')),
]



if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workspace/urls.py
from django.urls import path, include
from workspace import views


urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.workspace_create, name='workspace_create'),
    path('<int:workspace_id>/', views.get_workspace_boards, name='get_workspace_boards'),
    path('<int:workspace_id>/actions', views.workspace_actions, name='workspace_actions'),
    path('<int:workspace_id>/board/<int:board_id>/board_actions/', views.board_actions, name='board-actions'),
    path('invite/<uuid:workspace_uuid>/', views.workspace_invite_view, name='workspace-invite'),
]

workspace/models.py
from datetime import datetime
from django.db import models
from accounts.models import Users
from uuid import uuid4
from django.contrib.sites.models import Site

from django.urls import reverse
# Create your models here.

from django.db import models
from django.utils import timezone

class Workspace(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(
        'accounts.Users',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workspaces_created',
        db_index=True  # likely filtered by created_by
    )
    members = models.ManyToManyField(
        'accounts.Users',
        related_name='workspaces'
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    is_deleted = models.BooleanField(default=False, db_index=True)  # often filtered
    deleted_at = models.DateTimeField(null=True, blank=True)
    uuid       = models.UUIDField(default=uuid4, unique=True,)

    def __str__(self):
        return self.name

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save(update_fields=['is_deleted', 'deleted_at', 'updated_at'])
        return self
    
    def get_invite_link(self):
        relativeLink = reverse('workspace:workspace-invite', kwargs={'workspace_uuid': self.uuid})
        baseurl = Site.objects.get_current().domain
        invite_link = f"{baseurl}{relativeLink}"
        return invite_link

    class Meta:
        indexes = [
            models.Index(fields=['is_deleted']),
            models.Index(fields=['created_by']),
        ]

workspace/forms.py
from django import forms

from accounts.models import Users
from workspace.models import Workspace


class WorkSpaceForm(forms.ModelForm):
    members = forms.ModelMultipleChoiceField(required=False,widget=forms.CheckboxSelectMultiple(),queryset=Users.objects.none(),label='Add Members')

    def __init__(self, user,*args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.auto_id='edit_%s'
        else:
            self.auto_id='id_%s'
        self.user = user
        if self.user: 
            self.fields['members'].queryset = Users.objects.all().exclude(id=self.user.id)


        self.fields['members'].label_from_instance = lambda obj: f"{obj.name}" if obj.name else f"{obj.username}"
    
    def save(self, commit=True):
        """
        Save this form's self.instance object if commit=True. Otherwise, add
        a save_m2m() method to the form which can be called after the instance
        is saved manually at a later time. Return the model instance.
        """
        if self.errors:
            raise ValueError(
                "The %s could not be %s because the data didn't validate."
                % (
                    self.instance._meta.object_name,
                    "created" if self.instance._state.adding else "changed",
                )
            )
        if commit:
            # If committing, save the instance and the m2m data immediately.
            if self.instance and not self.instance.pk and self.user:
                self.instance.created_by = self.user
            self.instance.save()
            self._save_m2m()
        else:
            # If not committing, add a method to the form to allow deferred
            # saving of m2m data.
            self.save_m2m = self._save_m2m
        return self.instance

    class Meta:
        model = Workspace
        fields = ['name','members']

workspace/views.py
import json
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.db.models import QuerySet
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.core.paginator import Page
from board.forms import BoardCreateForm, BoardForm, TaskFilterForm
from board.models import Board
from notifications.views import get_notifications
from workspace.forms import WorkSpaceForm
from workspace.models import Workspace
from django_htmx.http import HttpResponseClientRedirect, HttpResponseClientRefresh
from task_manager.logger import logger
# Create your views here.



@require_http_methods(['GET',])
@login_required
def index(request):
    context = {}
    workspaces = Workspace.objects.filter(members=request.user).exclude(is_deleted=True)
    context["workspaces"] = workspaces
    context["form"] =  WorkSpaceForm(user=request.user)
    context['view_name'] = 'Workspace'
    return render(request, 'workspace/index.html',context)


@require_http_methods(['POST'])
@login_required
def workspace_create(request):
    form = WorkSpaceForm(user=request.user, data=request.POST)
    if form.is_valid():
        instance:Workspace = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        form.save_m2m()
        instance.members.add(instance.created_by)
        redirect_url = reverse('workspace:get_workspace_boards',kwargs={'workspace_id':instance.id})
        return HttpResponseClientRedirect(redirect_to=redirect_url)
    return render(request,"workspace/components/create.html",{'form':form})


@require_http_methods(['GET'])
@login_required
def get_workspace_boards(request,workspace_id):
    context = {}
    try:
        workspace = Workspace.objects.get(id=workspace_id, members=request.user)
        boards:QuerySet[Board] = Board.objects.prefetch_related('columns').filter(workspace=workspace, members=request.user).exclude(is_deleted=True)
        context['boards'] = boards
        context['workspace_id'] = workspace_id
        context['users'] = workspace.members.all()
        context['view_name'] = 'Board'
        context['board_create_form'] = BoardCreateForm(user=request.user)
        if request.GET.get('active_board'):
            context['active_board'] = request.user.board_memberships.filter(id=request.GET.get('active_board')).first()
        context:dict = get_notifications(user=request.user, page_number=1, context=context)
        return render(request,'boards/index.html',context)
    except Workspace.DoesNotExist:
        return redirect('workspace:index')


@require_http_methods(['GET','POST','DELETE'])
@login_required
def workspace_actions(request,workspace_id):
    try:
        workspace = Workspace.objects.get(id=workspace_id, created_by=request.user)
        if request.method=='DELETE':
            workspace.delete()
            response = HttpResponse(status=200)
            triggers = {}
            triggers["showToast"] = {"message":"Workspace Deleted", "level":"danger"}
            response['HX-Trigger'] = json.dumps(triggers)
            return response
        
        form = WorkSpaceForm(user=request.user,instance=workspace, data=request.POST or None)
        if request.method == 'POST' and form.is_valid():
            members = form.cleaned_data.get('members')
            
            members_list = list(members)
            members_list.append(workspace.created_by)
            
            # Save form but don't commit to DB yet
            instance = form.save(commit=False)
            
            # Manually set the modified members list
            instance.save()
            instance.members.set(members_list)  # assuming it's a ManyToMany field

            response = render(request, "workspace/components/workspace_card.html", {"workspace": instance})
            triggers = {'workspaceEdited':{'message':'Workspace Edited', 'level':'info'}}
            triggers["showToast"] = {"message":"Workspace Edited", "level":"success"}
            response['HX-Trigger'] = json.dumps(triggers)
            return response
        return render(request,'workspace/components/edit.html',{'form':form})
    except Exception as e:
        logger.exception(stack_info=False, msg=str(e))
        if request.htmx:
            redirect_url = reverse('workspace:index')
            return HttpResponseClientRedirect(redirect_to=redirect_url)
        return redirect('workspace:index')



@require_http_methods(['GET','POST','DELETE'])
@login_required
def board_actions(request,workspace_id,board_id):
    try:
        board:Board = Board.objects.get(workspace_id=workspace_id,id=board_id, created_by=request.user)
        if request.method=='DELETE':
            board.delete()
            response = HttpResponseClientRefresh()
            triggers = {}
            triggers["showToast"] = {"message":"Board Deleted", "level":"danger"}
            response['HX-Trigger'] = json.dumps(triggers)
            return response
            
        form = BoardForm(workspace=board.workspace,user=request.user, instance=board, data=request.POST or None)
        if request.method == 'POST' and form.is_valid():
            members = form.cleaned_data.get('members')
            
            members_list = list(members)
            members_list.append(board.created_by)

            instance:Board = form.save(commit=False)
            # Manually set the modified members list
            instance.save()
            instance.members.set(members_list)  # assuming it's a ManyToMany field

            response = render(request,'boards/components/board_list_item.html',{'board':instance})
            triggers = {}
            triggers["closeModal"] = {"modal_id": "close_editBoardModal", "level": "info"}
            triggers["showToast"] = {"message":"Board Detail Edited", "level":"success"}
            response['HX-Trigger'] = json.dumps(triggers)
            return response
        return render(request,'boards/components/board_edit.html',{'form':form})
    except Exception as e:
        logger.exception(stack_info=False, msg=str(e))
        if request.htmx:
            redirect_url = reverse('workspace:index')
            return HttpResponseClientRedirect(redirect_to=redirect_url)
        return redirect('workspace:index')




@login_required
def workspace_invite_view(request, workspace_uuid):
    try:
        workspace = Workspace.objects.get(uuid=workspace_uuid)
        user = request.user

        if user in workspace.members.all():
            # Already a member, redirect to workspace index
            return redirect('workspace:get_workspace_boards', workspace_id=workspace.id)

        if request.method == 'POST':
            # User confirms joining
            workspace.members.add(user)
            return redirect('workspace:get_workspace_boards', workspace_id=workspace.id)

        # Show confirmation page
        return render(request, 'workspace/invite_confirmation.html', {
            'workspace': workspace
        })
    except Workspace.DoesNotExist:
        return redirect('workspace:index')

templates/workspace/components/create.html
<form id="create_workspace_form" 
    method="POST"
    action="{% url 'workspace:workspace_create' %}" 
    hx-post="{% url 'workspace:workspace_create' %}" 
    hx-target="#workspaces" 
    hx-swap="beforeend">
    {% include 'form.html' with form=form %}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Cancel</button>
    </div>
</form>

templates/workspace/components/edit.html
<form id="edit_workspace_form" 
    method="POST"
    action="{% url 'workspace:workspace_actions' form.instance.id %}" 
    hx-post="{% url 'workspace:workspace_actions' form.instance.id %}" 
    hx-target="#workspace-{{ form.instance.id }}" 
    hx-swap="outerHTML">
    {% include 'form.html' with form=form %}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Cancel</button>
    </div>
</form>

templates/workspace/components/workspace_card.html
{% comment %} <div class="col" id="workspace-{{ workspace.id }}">
    <div class="workspace card h-100 rounded-4 border-0">
        <div class="card-body">
            <h5 class="card-title fw-semibold">{{ workspace.name }}</h5>
        </div>
        <div class="card-footer bg-white border-0 d-flex align-items-center px-3 pb-3">
            <div class="ms-auto d-flex gap-2">
                <a href="{% url 'workspace:get_workspace_boards' workspace.id %}" class="btn btn-outline-primary btn-sm" title="View">
                    <i class="fas fa-arrow-right"></i>
                </a>
                {% if workspace.created_by == request.user %}
                <button class="btn btn-outline-secondary btn-sm" title="Edit Workspace"
                        hx-get="{% url 'workspace:workspace_actions' workspace.id %}"
                        hx-target="#editWorkspaceModalContent"
                        data-bs-toggle="modal"
                        data-bs-target="#editWorkspaceModal">
                    <i class="fas fa-pen"></i>
                </button>
                <button class="btn btn-outline-danger btn-sm" title="Delete Workspace"
                        hx-delete="{% url 'workspace:workspace_actions' workspace.id %}"
                        hx-target="#workspace-{{ workspace.id }}"
                        hx-swap="delete"
                        hx-confirm="Are you sure?">
                    <i class="fas fa-trash"></i>
                </button>
                {% endif %}
            </div>
        </div>
    </div>
</div> {% endcomment %}

<div class="col-sm-6 col-md-4 col-lg-3" id="workspace-{{ workspace.id }}">
    <div class="card card-glass h-100 shadow-sm p-3">
      <div class="card-body d-flex flex-column justify-content-between">
        <div class="workspace-title mb-4">{{ workspace.name }}</div>
        <div class="d-flex justify-content-end gap-2">
          <a role="button" href="{% url 'workspace:get_workspace_boards' workspace.id %}" class="btn btn-outline-primary btn-icon" title="View Workspace">
            <i class="fas fa-arrow-right"></i>
          </a>
          <button onclick="copyToClipboard(this)" data-copy="{{workspace.get_invite_link}}" class="btn btn-outline-primary btn-icon" title="Invite Link">
            <i class="fa-solid fa-link"></i>
          </button>
          {% if workspace.created_by == request.user %}
          <button class="btn btn-outline-secondary btn-icon" title="Edit Workspace"
                hx-get="{% url 'workspace:workspace_actions' workspace.id %}"
                hx-target="#editWorkspaceModalContent"
                data-bs-toggle="modal"
                data-bs-target="#editWorkspaceModal">
            <i class="fas fa-pen"></i>
          </button>
          <button class="btn btn-outline-danger btn-icon" title="Delete Workspace"
                hx-delete="{% url 'workspace:workspace_actions' workspace.id %}"
                hx-target="#workspace-{{ workspace.id }}"
                hx-swap="delete"
                hx-confirm="Are you sure?">
            <i class="fas fa-trash-alt"></i>
          </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>